apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-a-readwrite
  namespace: team-a
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]